"""Opponent Q&A, grounded strictly in the precomputed tables.

An experiment, off by default: the endpoint exists only when
ANTHROPIC_API_KEY is set, so the core product never depends on an external
API (see ROADMAP.md). Answers are generated by Claude from a context bundle
assembled out of the same derived tables the dashboard reads — the model is
instructed to answer only from that data and to cite numbers and sample
sizes, and to say plainly when the data cannot answer the question.
"""

import json
import os
from typing import Any

from backend import queries

MODEL = "claude-opus-5"

LANES = ["left wing", "left half-space", "central", "right half-space", "right wing"]

SYSTEM_PROMPT = """You are an assistant for a professional football match analyst, \
answering questions about an upcoming opponent.

Rules:
- Answer ONLY from the data provided in the message. Never use outside knowledge \
about teams, players, or matches — not even facts you are confident about.
- Cite the numbers and sample sizes behind every claim (e.g. "12 of 21 corners \
were played short").
- If the data cannot answer the question, say so plainly and name what data \
would be needed. Do not guess.
- Use correct football terminology (half-spaces, build-up, first contact).
- Be concise: an analyst reads this between meetings. 2-6 sentences unless the \
question genuinely needs more.
- Data caveats: this is one tournament (3-7 matches per team); xT is expected \
threat from completed passes and carries."""


def is_enabled() -> bool:
    return bool(os.environ.get("ANTHROPIC_API_KEY"))


def _zone_name(zone_x: int, zone_y: int) -> str:
    third = "own third" if zone_x < 4 else "middle third" if zone_x < 8 else "final third"
    return f"{third} / {LANES[min(4, (zone_y * 10) // 16)]}"


def build_context(team_id: int, competition_id: int, season_id: int) -> dict[str, Any] | None:
    """The grounded data bundle the model is allowed to answer from."""
    report = queries.report(team_id, competition_id, season_id)
    if report is None:
        return None
    zones = queries.threat_map(team_id, competition_id, season_id)
    top_zones = sorted(zones, key=lambda z: -z["xt"])[:10]
    total_xt = sum(z["xt"] for z in zones) or 1.0
    return {
        "team": report["profile"]["team"]["name"],
        "record": report["profile"]["record"],
        "possession_summary": report["profile"]["threat"],
        "matches": report["profile"]["matches"],
        "top_threat_zones": [
            {
                "zone": _zone_name(z["zone_x"], z["zone_y"]),
                "share_of_team_threat": round(z["xt"] / total_xt, 3),
                "n_actions": z["n_actions"],
                "n_pressured_actions": z["n_pressured"],
                "share_of_zone_threat_under_pressure": (
                    round(z["xt_pressured"] / z["xt"], 2) if z["xt"] else 0
                ),
            }
            for z in top_zones
        ],
        "build_up_patterns": report["patterns"],
        "corner_delivery_zones": report["set_pieces"],
        "player_watchlist": report["watchlist"],
    }


def ask(
    team_id: int, competition_id: int, season_id: int, question: str
) -> dict[str, Any] | None:
    """Returns {"answer": str, "model": str} or None for an unknown team."""
    import anthropic

    context = build_context(team_id, competition_id, season_id)
    if context is None:
        return None

    client = anthropic.Anthropic()
    response = client.beta.messages.create(
        model=MODEL,
        max_tokens=1024,
        betas=["server-side-fallback-2026-07-01"],
        fallbacks="default",
        system=SYSTEM_PROMPT,
        messages=[
            {
                "role": "user",
                "content": (
                    "Opponent data (the only source you may use):\n"
                    f"{json.dumps(context, default=str)}\n\n"
                    f"Analyst question: {question}"
                ),
            }
        ],
    )
    if response.stop_reason == "refusal":
        return {
            "answer": "The model declined to answer this question. "
            "Try rephrasing it as a football-analysis question.",
            "model": response.model,
        }
    answer = next((b.text for b in response.content if b.type == "text"), "")
    return {"answer": answer, "model": response.model}
